import React, { Component } from 'react'

export class Card extends Component {
  render() {
    return React.createElement('div',{className:"wrapper"},React.createElement('div',{className:"table basic"},
    React.createElement('div',{className:"price-section"},
    React.createElement('div',{className:"inner-area"},
    React.createElement('span',{className:"text"},"$."),
    React.createElement('span',{className:"price"},"00"))),
    React.createElement('div',{className:"package-name"},""),
    React.createElement('div',{className:"features"},
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"one Selected Template"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"fas fa-check-circle"},null))),
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"100% Responsive Design"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"fas fa-check-circle"},null))),
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"Credit Remove Permission"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"far fa-times-circle"},null))),
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"Lifetime Template Updates"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"far fa-times-circle"},null))),
    React.createElement('div',{className:"btn"},React.createElement('button',null,"Purchase")))),
    React.createElement('div',{className:"table Premium"},
    React.createElement('div',{className:"price-section"},
    React.createElement('div',{className:"inner-area"},
    React.createElement('span',{className:"text"},"$."),
    React.createElement('span',{className:"price"},"28"))),
    React.createElement('div',{className:"package-name"},""),
    React.createElement('div',{className:"features"},
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"Five Selected Template"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"fas fa-check-circle"},null))),
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"100% Responsive Design"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"fas fa-check-circle"},null))),
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"Credit Remove Permission"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"fas fa-check-circle"},null))),
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"Lifetime Template Updates"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"far fa-times-circle"},null))),
    React.createElement('div',{className:"btn"},React.createElement('button',null,"Purchase")))),
    React.createElement('div',{className:"table Ultimate"},
    React.createElement('div',{className:"price-section"},
    React.createElement('div',{className:"inner-area"},
    React.createElement('span',{className:"text"},"$."),
    React.createElement('span',{className:"price"},"49"))),
    React.createElement('div',{className:"package-name"},""),
    React.createElement('div',{className:"features"},
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"All Selected Template"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"fas fa-check-circle"},null))),
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"100% Responsive Design"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"fas fa-check-circle"},null))),
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"Credit Remove Permission"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"fas fa-check-circle"},null))),
    React.createElement('li',null,React.createElement('span',{className:"list-name"},"Lifetime Template Updates"),
    React.createElement('span',{className:"icon check"},React.createElement('i',{className:"fas fa-check-circle"},null))),
    React.createElement('div',{className:"btn"},React.createElement('button',null,"Purchase"))) ))
  }
}

export default Card